site_name: My Docs
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    anchors: info
    absolute_links: relative_to_docs
    unrecognized_links: info
nav:
  - Home: 'index.md'
  - 'User Guide': 'hello.md'
